// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Notification struct {
	ID               uuid.UUID   `json:"id"`
	EventID          string      `json:"event_id"`
	NotificationType string      `json:"notification_type"`
	Category         string      `json:"category"`
	RecipientID      string      `json:"recipient_id"`
	Payload          []byte      `json:"payload"`
	TraceID          pgtype.Text `json:"trace_id"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type NotificationDelivery struct {
	ID             uuid.UUID          `json:"id"`
	NotificationID uuid.UUID          `json:"notification_id"`
	Channel        string             `json:"channel"`
	Provider       pgtype.Text        `json:"provider"`
	Destination    string             `json:"destination"`
	Status         string             `json:"status"`
	RetryCount     int32              `json:"retry_count"`
	MaxRetries     int32              `json:"max_retries"`
	NextRetryAt    pgtype.Timestamptz `json:"next_retry_at"`
	LockedBy       pgtype.Text        `json:"locked_by"`
	LockedAt       pgtype.Timestamptz `json:"locked_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
}

type NotificationDeliveryAttempt struct {
	ID                uuid.UUID   `json:"id"`
	DeliveryID        uuid.UUID   `json:"delivery_id"`
	AttemptNumber     int32       `json:"attempt_number"`
	Provider          string      `json:"provider"`
	ProviderMessageID pgtype.Text `json:"provider_message_id"`
	Status            string      `json:"status"`
	HttpStatusCode    pgtype.Int4 `json:"http_status_code"`
	ErrorType         pgtype.Text `json:"error_type"`
	ErrorMessage      pgtype.Text `json:"error_message"`
	Response          []byte      `json:"response"`
	CreatedAt         time.Time   `json:"created_at"`
}

type Provider struct {
	Name      string    `json:"name"`
	Type      string    `json:"type"`
	Config    []byte    `json:"config"`
	Priority  int32     `json:"priority"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
