// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_deliveries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelDelivery = `-- name: CancelDelivery :one
UPDATE notification_deliveries
SET
    status = 'cancelled',
    next_retry_at = NULL,
    locked_by = NULL,
    locked_at = NULL
WHERE id = $1
  AND status IN ('pending', 'retry')
    RETURNING id, notification_id, channel, provider, destination, status, retry_count, max_retries, next_retry_at, locked_by, locked_at, created_at, updated_at, sent_at
`

func (q *Queries) CancelDelivery(ctx context.Context, id uuid.UUID) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, cancelDelivery, id)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Channel,
		&i.Provider,
		&i.Destination,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}

const claimDeliveries = `-- name: ClaimDeliveries :many
WITH candidates AS (
    SELECT id
    FROM notification_deliveries
    WHERE status = 'pending'
       OR (
        status = 'retry'
            AND next_retry_at <= now()
        )
    ORDER BY
        COALESCE(next_retry_at, created_at),
        created_at,
        id
    FOR UPDATE SKIP LOCKED
    LIMIT $2
)
UPDATE notification_deliveries AS d
SET
    status = 'processing',
    locked_by = $1,
    locked_at = now()
    FROM candidates
WHERE d.id = candidates.id
    RETURNING d.id, d.notification_id, d.channel, d.provider, d.destination, d.status, d.retry_count, d.max_retries, d.next_retry_at, d.locked_by, d.locked_at, d.created_at, d.updated_at, d.sent_at
`

type ClaimDeliveriesParams struct {
	WorkerID  pgtype.Text `json:"worker_id"`
	BatchSize int32       `json:"batch_size"`
}

func (q *Queries) ClaimDeliveries(ctx context.Context, arg ClaimDeliveriesParams) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, claimDeliveries, arg.WorkerID, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.Channel,
			&i.Provider,
			&i.Destination,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.LockedBy,
			&i.LockedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimNextDelivery = `-- name: ClaimNextDelivery :one
WITH candidate AS (
    SELECT id
    FROM notification_deliveries
    WHERE status = 'pending'
       OR (
        status = 'retry'
            AND next_retry_at <= now()
        )
    ORDER BY
        COALESCE(next_retry_at, created_at),
        created_at,
        id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE notification_deliveries AS d
SET
    status = 'processing',
    locked_by = $1,
    locked_at = now()
    FROM candidate
WHERE d.id = candidate.id
    RETURNING d.id, d.notification_id, d.channel, d.provider, d.destination, d.status, d.retry_count, d.max_retries, d.next_retry_at, d.locked_by, d.locked_at, d.created_at, d.updated_at, d.sent_at
`

func (q *Queries) ClaimNextDelivery(ctx context.Context, workerID pgtype.Text) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, claimNextDelivery, workerID)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Channel,
		&i.Provider,
		&i.Destination,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}

const createNotificationDelivery = `-- name: CreateNotificationDelivery :one
INSERT INTO notification_deliveries (
    notification_id,
    channel,
    provider,
    destination,
    max_retries
)
VALUES (
           $1,
           $2,
           $3,
           $4,
           $5
       )
    RETURNING id, notification_id, channel, provider, destination, status, retry_count, max_retries, next_retry_at, locked_by, locked_at, created_at, updated_at, sent_at
`

type CreateNotificationDeliveryParams struct {
	NotificationID uuid.UUID   `json:"notification_id"`
	Channel        string      `json:"channel"`
	Provider       pgtype.Text `json:"provider"`
	Destination    string      `json:"destination"`
	MaxRetries     int32       `json:"max_retries"`
}

func (q *Queries) CreateNotificationDelivery(ctx context.Context, arg CreateNotificationDeliveryParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, createNotificationDelivery,
		arg.NotificationID,
		arg.Channel,
		arg.Provider,
		arg.Destination,
		arg.MaxRetries,
	)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Channel,
		&i.Provider,
		&i.Destination,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}

const getDeliveryByID = `-- name: GetDeliveryByID :one
SELECT id, notification_id, channel, provider, destination, status, retry_count, max_retries, next_retry_at, locked_by, locked_at, created_at, updated_at, sent_at
FROM notification_deliveries
WHERE id = $1
`

func (q *Queries) GetDeliveryByID(ctx context.Context, id uuid.UUID) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, getDeliveryByID, id)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Channel,
		&i.Provider,
		&i.Destination,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}

const getDeliveryByNotificationAndChannel = `-- name: GetDeliveryByNotificationAndChannel :one
SELECT id, notification_id, channel, provider, destination, status, retry_count, max_retries, next_retry_at, locked_by, locked_at, created_at, updated_at, sent_at
FROM notification_deliveries
WHERE notification_id = $1
  AND channel = $2
`

type GetDeliveryByNotificationAndChannelParams struct {
	NotificationID uuid.UUID `json:"notification_id"`
	Channel        string    `json:"channel"`
}

func (q *Queries) GetDeliveryByNotificationAndChannel(ctx context.Context, arg GetDeliveryByNotificationAndChannelParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, getDeliveryByNotificationAndChannel, arg.NotificationID, arg.Channel)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Channel,
		&i.Provider,
		&i.Destination,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}

const listDeliveriesByNotificationID = `-- name: ListDeliveriesByNotificationID :many
SELECT id, notification_id, channel, provider, destination, status, retry_count, max_retries, next_retry_at, locked_by, locked_at, created_at, updated_at, sent_at
FROM notification_deliveries
WHERE notification_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListDeliveriesByNotificationID(ctx context.Context, notificationID uuid.UUID) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, listDeliveriesByNotificationID, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.Channel,
			&i.Provider,
			&i.Destination,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.LockedBy,
			&i.LockedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliveryFailed = `-- name: MarkDeliveryFailed :one
UPDATE notification_deliveries
SET
    status = 'failed',
    next_retry_at = NULL,
    locked_by = NULL,
    locked_at = NULL
WHERE id = $1
  AND status = 'processing'
  AND locked_by = $2
    RETURNING id, notification_id, channel, provider, destination, status, retry_count, max_retries, next_retry_at, locked_by, locked_at, created_at, updated_at, sent_at
`

type MarkDeliveryFailedParams struct {
	ID       uuid.UUID   `json:"id"`
	WorkerID pgtype.Text `json:"worker_id"`
}

func (q *Queries) MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, markDeliveryFailed, arg.ID, arg.WorkerID)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Channel,
		&i.Provider,
		&i.Destination,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}

const markDeliverySent = `-- name: MarkDeliverySent :one
UPDATE notification_deliveries
SET
    status = 'sent',
    sent_at = now(),
    next_retry_at = NULL,
    locked_by = NULL,
    locked_at = NULL
WHERE id = $1
  AND status = 'processing'
  AND locked_by = $2
    RETURNING id, notification_id, channel, provider, destination, status, retry_count, max_retries, next_retry_at, locked_by, locked_at, created_at, updated_at, sent_at
`

type MarkDeliverySentParams struct {
	ID       uuid.UUID   `json:"id"`
	WorkerID pgtype.Text `json:"worker_id"`
}

func (q *Queries) MarkDeliverySent(ctx context.Context, arg MarkDeliverySentParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, markDeliverySent, arg.ID, arg.WorkerID)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Channel,
		&i.Provider,
		&i.Destination,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}

const reclaimStaleDeliveries = `-- name: ReclaimStaleDeliveries :many
UPDATE notification_deliveries
SET
    status = CASE
                 WHEN retry_count < max_retries THEN 'retry'
                 ELSE 'failed'
        END,
    retry_count = CASE
                      WHEN retry_count < max_retries THEN retry_count + 1
                      ELSE retry_count
        END,
    next_retry_at = CASE
                        WHEN retry_count < max_retries THEN now()
                        ELSE NULL
        END,
    locked_by = NULL,
    locked_at = NULL
WHERE status = 'processing'
  AND locked_at < now() - $1::interval
RETURNING id, notification_id, channel, provider, destination, status, retry_count, max_retries, next_retry_at, locked_by, locked_at, created_at, updated_at, sent_at
`

func (q *Queries) ReclaimStaleDeliveries(ctx context.Context, leaseTimeout pgtype.Interval) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, reclaimStaleDeliveries, leaseTimeout)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.Channel,
			&i.Provider,
			&i.Destination,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.LockedBy,
			&i.LockedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scheduleDeliveryRetry = `-- name: ScheduleDeliveryRetry :one
UPDATE notification_deliveries
SET
    status = 'retry',
    retry_count = retry_count + 1,
    next_retry_at = $1,
    locked_by = NULL,
    locked_at = NULL
WHERE id = $2
  AND status = 'processing'
  AND locked_by = $3
  AND retry_count < max_retries
    RETURNING id, notification_id, channel, provider, destination, status, retry_count, max_retries, next_retry_at, locked_by, locked_at, created_at, updated_at, sent_at
`

type ScheduleDeliveryRetryParams struct {
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	ID          uuid.UUID          `json:"id"`
	WorkerID    pgtype.Text        `json:"worker_id"`
}

func (q *Queries) ScheduleDeliveryRetry(ctx context.Context, arg ScheduleDeliveryRetryParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, scheduleDeliveryRetry, arg.NextRetryAt, arg.ID, arg.WorkerID)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Channel,
		&i.Provider,
		&i.Destination,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}
