// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_deliveries.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDelivery = `-- name: ClaimDelivery :one
UPDATE notification_deliveries
SET status     = 'processing',
    locked_at  = NOW(),
    locked_by  = $2,
    updated_at = NOW()
WHERE id = $1
  AND (
    status = 'pending'
        OR (
        status = 'retry'
            AND next_retry_at <= NOW()
        )
    )
  AND (
    locked_at IS NULL
        OR locked_at < NOW() - INTERVAL '5 minutes'
    )
    RETURNING
    id,
    notification_id,
    channel,
    provider,
    destination,
    status,
    retry_count,
    max_retries,
    next_retry_at,
    locked_by,
    locked_at,
    created_at,
    updated_at,
    sent_at
`

type ClaimDeliveryParams struct {
	ID       uuid.UUID   `json:"id"`
	LockedBy pgtype.Text `json:"locked_by"`
}

func (q *Queries) ClaimDelivery(ctx context.Context, arg ClaimDeliveryParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, claimDelivery, arg.ID, arg.LockedBy)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Channel,
		&i.Provider,
		&i.Destination,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}

const createNotificationDelivery = `-- name: CreateNotificationDelivery :one
INSERT INTO notification_deliveries (notification_id,
                                     channel,
                                     provider,
                                     destination,
                                     status,
                                     retry_count,
                                     max_retries)
VALUES ($1,
        $2,
        $3,
        $4,
        'pending',
        0,
        $5) RETURNING id, notification_id, channel, provider, destination, status, retry_count, max_retries, next_retry_at, locked_by, locked_at, created_at, updated_at, sent_at
`

type CreateNotificationDeliveryParams struct {
	NotificationID uuid.UUID `json:"notification_id"`
	Channel        string    `json:"channel"`
	Provider       string    `json:"provider"`
	Destination    string    `json:"destination"`
	MaxRetries     int32     `json:"max_retries"`
}

func (q *Queries) CreateNotificationDelivery(ctx context.Context, arg CreateNotificationDeliveryParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, createNotificationDelivery,
		arg.NotificationID,
		arg.Channel,
		arg.Provider,
		arg.Destination,
		arg.MaxRetries,
	)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Channel,
		&i.Provider,
		&i.Destination,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}

const getDeliveryByID = `-- name: GetDeliveryByID :one
SELECT id,
       notification_id,
       channel,
       provider,
       destination,
       status,
       retry_count,
       max_retries,
       next_retry_at,
       locked_by,
       locked_at,
       created_at,
       updated_at,
       sent_at
FROM notification_deliveries
WHERE id = $1
`

func (q *Queries) GetDeliveryByID(ctx context.Context, id uuid.UUID) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, getDeliveryByID, id)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Channel,
		&i.Provider,
		&i.Destination,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
	)
	return i, err
}

const getDeliveryWithNotification = `-- name: GetDeliveryWithNotification :one
SELECT d.id,
       d.notification_id,
       d.channel,
       d.provider,
       d.destination,
       d.status,
       d.retry_count,
       d.max_retries,
       d.next_retry_at,
       d.locked_by,
       d.locked_at,
       d.created_at,
       d.updated_at,
       d.sent_at,
       n.notification_type,
       n.category,
       n.payload AS notification_payload
FROM notification_deliveries AS d
         JOIN notifications AS n
              ON n.id = d.notification_id
WHERE d.id = $1
`

type GetDeliveryWithNotificationRow struct {
	ID                  uuid.UUID          `json:"id"`
	NotificationID      uuid.UUID          `json:"notification_id"`
	Channel             string             `json:"channel"`
	Provider            string             `json:"provider"`
	Destination         string             `json:"destination"`
	Status              string             `json:"status"`
	RetryCount          int32              `json:"retry_count"`
	MaxRetries          int32              `json:"max_retries"`
	NextRetryAt         pgtype.Timestamptz `json:"next_retry_at"`
	LockedBy            pgtype.Text        `json:"locked_by"`
	LockedAt            pgtype.Timestamptz `json:"locked_at"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	SentAt              pgtype.Timestamptz `json:"sent_at"`
	NotificationType    string             `json:"notification_type"`
	Category            string             `json:"category"`
	NotificationPayload []byte             `json:"notification_payload"`
}

func (q *Queries) GetDeliveryWithNotification(ctx context.Context, id uuid.UUID) (GetDeliveryWithNotificationRow, error) {
	row := q.db.QueryRow(ctx, getDeliveryWithNotification, id)
	var i GetDeliveryWithNotificationRow
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Channel,
		&i.Provider,
		&i.Destination,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
		&i.NotificationType,
		&i.Category,
		&i.NotificationPayload,
	)
	return i, err
}

const listReadyRetryDeliveries = `-- name: ListReadyRetryDeliveries :many
SELECT id
FROM notification_deliveries
WHERE status = 'retry'
  AND next_retry_at IS NOT NULL
  AND next_retry_at <= $1
ORDER BY next_retry_at,
         created_at,
         id LIMIT $2
`

type ListReadyRetryDeliveriesParams struct {
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	Limit       int32              `json:"limit"`
}

func (q *Queries) ListReadyRetryDeliveries(ctx context.Context, arg ListReadyRetryDeliveriesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listReadyRetryDeliveries, arg.NextRetryAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliveryFailed = `-- name: MarkDeliveryFailed :execrows
UPDATE notification_deliveries
SET status        = 'failed',
    next_retry_at = NULL,
    locked_at     = NULL,
    locked_by     = NULL,
    updated_at    = NOW()
WHERE id = $1
  AND status = 'processing'
  AND locked_by = $2
`

type MarkDeliveryFailedParams struct {
	ID       uuid.UUID   `json:"id"`
	LockedBy pgtype.Text `json:"locked_by"`
}

func (q *Queries) MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDeliveryFailed, arg.ID, arg.LockedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDeliveryRetry = `-- name: MarkDeliveryRetry :execrows
UPDATE notification_deliveries
SET status        = 'retry',
    retry_count   = retry_count + 1,
    next_retry_at = $2,
    locked_at     = NULL,
    locked_by     = NULL,
    updated_at    = NOW()
WHERE id = $1
  AND status = 'processing'
  AND locked_by = $3
  AND retry_count < max_retries
`

type MarkDeliveryRetryParams struct {
	ID          uuid.UUID          `json:"id"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	LockedBy    pgtype.Text        `json:"locked_by"`
}

func (q *Queries) MarkDeliveryRetry(ctx context.Context, arg MarkDeliveryRetryParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDeliveryRetry, arg.ID, arg.NextRetryAt, arg.LockedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDeliverySent = `-- name: MarkDeliverySent :execrows
UPDATE notification_deliveries
SET status        = 'sent',
    sent_at       = NOW(),
    next_retry_at = NULL,
    locked_at     = NULL,
    locked_by     = NULL,
    updated_at    = NOW()
WHERE id = $1
  AND status = 'processing'
  AND locked_by = $2
`

type MarkDeliverySentParams struct {
	ID       uuid.UUID   `json:"id"`
	LockedBy pgtype.Text `json:"locked_by"`
}

func (q *Queries) MarkDeliverySent(ctx context.Context, arg MarkDeliverySentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDeliverySent, arg.ID, arg.LockedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reclaimAbandonedDeliveries = `-- name: ReclaimAbandonedDeliveries :many
UPDATE notification_deliveries
SET status     = 'pending',
    locked_by  = NULL,
    locked_at  = NULL,
    updated_at = NOW()
WHERE status = 'processing'
  AND locked_at IS NOT NULL
  AND locked_at < $1 RETURNING id, notification_id, channel, provider, destination, status, retry_count, max_retries, next_retry_at, locked_by, locked_at, created_at, updated_at, sent_at
`

func (q *Queries) ReclaimAbandonedDeliveries(ctx context.Context, lockedAt pgtype.Timestamptz) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, reclaimAbandonedDeliveries, lockedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.Channel,
			&i.Provider,
			&i.Destination,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.LockedBy,
			&i.LockedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
