// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    event_id,
    notification_type,
    category,
    recipient_id,
    payload,
    trace_id
)
VALUES (
           $1,
           $2,
           $3,
           $4,
           $5,
           $6
       )
    RETURNING id, event_id, notification_type, category, recipient_id, payload, trace_id, created_at, updated_at
`

type CreateNotificationParams struct {
	EventID          string      `json:"event_id"`
	NotificationType string      `json:"notification_type"`
	Category         string      `json:"category"`
	RecipientID      string      `json:"recipient_id"`
	Payload          []byte      `json:"payload"`
	TraceID          pgtype.Text `json:"trace_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.EventID,
		arg.NotificationType,
		arg.Category,
		arg.RecipientID,
		arg.Payload,
		arg.TraceID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.NotificationType,
		&i.Category,
		&i.RecipientID,
		&i.Payload,
		&i.TraceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationByEventID = `-- name: GetNotificationByEventID :one
SELECT id, event_id, notification_type, category, recipient_id, payload, trace_id, created_at, updated_at
FROM notifications
WHERE event_id = $1
`

func (q *Queries) GetNotificationByEventID(ctx context.Context, eventID string) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByEventID, eventID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.NotificationType,
		&i.Category,
		&i.RecipientID,
		&i.Payload,
		&i.TraceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
