// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_delivery_attempts.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDeliveryAttempt = `-- name: CreateDeliveryAttempt :one
INSERT INTO notification_delivery_attempts (
    delivery_id,
    attempt_number,
    provider,
    provider_message_id,
    status,
    http_status_code,
    error_type,
    error_message,
    response
)
VALUES (
           $1,
           $2,
           $3,
           $4,
           $5,
           $6,
           $7,
           $8,
           $9
       )
    RETURNING id, delivery_id, attempt_number, provider, provider_message_id, status, http_status_code, error_type, error_message, response, created_at
`

type CreateDeliveryAttemptParams struct {
	DeliveryID        uuid.UUID   `json:"delivery_id"`
	AttemptNumber     int32       `json:"attempt_number"`
	Provider          string      `json:"provider"`
	ProviderMessageID pgtype.Text `json:"provider_message_id"`
	Status            string      `json:"status"`
	HttpStatusCode    pgtype.Int4 `json:"http_status_code"`
	ErrorType         pgtype.Text `json:"error_type"`
	ErrorMessage      pgtype.Text `json:"error_message"`
	Response          []byte      `json:"response"`
}

func (q *Queries) CreateDeliveryAttempt(ctx context.Context, arg CreateDeliveryAttemptParams) (NotificationDeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, createDeliveryAttempt,
		arg.DeliveryID,
		arg.AttemptNumber,
		arg.Provider,
		arg.ProviderMessageID,
		arg.Status,
		arg.HttpStatusCode,
		arg.ErrorType,
		arg.ErrorMessage,
		arg.Response,
	)
	var i NotificationDeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.AttemptNumber,
		&i.Provider,
		&i.ProviderMessageID,
		&i.Status,
		&i.HttpStatusCode,
		&i.ErrorType,
		&i.ErrorMessage,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const getDeliveryAttempts = `-- name: GetDeliveryAttempts :many
SELECT
    id,
    delivery_id,
    attempt_number,
    provider,
    provider_message_id,
    status,
    http_status_code,
    error_type,
    error_message,
    response,
    created_at
FROM notification_delivery_attempts
WHERE delivery_id = $1
ORDER BY attempt_number ASC
`

func (q *Queries) GetDeliveryAttempts(ctx context.Context, deliveryID uuid.UUID) ([]NotificationDeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, getDeliveryAttempts, deliveryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDeliveryAttempt{}
	for rows.Next() {
		var i NotificationDeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.AttemptNumber,
			&i.Provider,
			&i.ProviderMessageID,
			&i.Status,
			&i.HttpStatusCode,
			&i.ErrorType,
			&i.ErrorMessage,
			&i.Response,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestDeliveryAttempt = `-- name: GetLatestDeliveryAttempt :one
SELECT
    id,
    delivery_id,
    attempt_number,
    provider,
    provider_message_id,
    status,
    http_status_code,
    error_type,
    error_message,
    response,
    created_at
FROM notification_delivery_attempts
WHERE delivery_id = $1
ORDER BY attempt_number DESC
    LIMIT 1
`

func (q *Queries) GetLatestDeliveryAttempt(ctx context.Context, deliveryID uuid.UUID) (NotificationDeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, getLatestDeliveryAttempt, deliveryID)
	var i NotificationDeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.AttemptNumber,
		&i.Provider,
		&i.ProviderMessageID,
		&i.Status,
		&i.HttpStatusCode,
		&i.ErrorType,
		&i.ErrorMessage,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}
