// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: providers.sql

package repository

import (
	"context"
)

const deactivateProvider = `-- name: DeactivateProvider :one
UPDATE providers
SET is_active = false
WHERE name = $1 RETURNING name, type, config, priority, is_active, created_at, updated_at
`

func (q *Queries) DeactivateProvider(ctx context.Context, name string) (Provider, error) {
	row := q.db.QueryRow(ctx, deactivateProvider, name)
	var i Provider
	err := row.Scan(
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderByName = `-- name: GetProviderByName :one
SELECT name, type, config, priority, is_active, created_at, updated_at
FROM providers
WHERE name = $1
`

func (q *Queries) GetProviderByName(ctx context.Context, name string) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByName, name)
	var i Provider
	err := row.Scan(
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProvidersByType = `-- name: ListActiveProvidersByType :many
SELECT name, type, config, priority, is_active, created_at, updated_at
FROM providers
WHERE type = $1
  AND is_active = true
ORDER BY priority ASC, name ASC
`

func (q *Queries) ListActiveProvidersByType(ctx context.Context, type_ string) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listActiveProvidersByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.Name,
			&i.Type,
			&i.Config,
			&i.Priority,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProvider = `-- name: UpsertProvider :one
INSERT INTO providers (name,
                       type,
                       config,
                       priority,
                       is_active)
VALUES ($1,
        $2,
        $3,
        $4,
        $5) ON CONFLICT (name)
DO
UPDATE SET
    type = EXCLUDED.type,
    config = EXCLUDED.config,
    priority = EXCLUDED.priority,
    is_active = EXCLUDED.is_active
    RETURNING name, type, config, priority, is_active, created_at, updated_at
`

type UpsertProviderParams struct {
	Name     string `json:"name"`
	Type     string `json:"type"`
	Config   []byte `json:"config"`
	Priority int32  `json:"priority"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) UpsertProvider(ctx context.Context, arg UpsertProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, upsertProvider,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.Priority,
		arg.IsActive,
	)
	var i Provider
	err := row.Scan(
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
