// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: providers.sql

package repository

import (
	"context"
)

const getProviderByName = `-- name: GetProviderByName :one
SELECT name, type, config, priority, is_active, created_at, updated_at
FROM providers
WHERE name = $1
`

func (q *Queries) GetProviderByName(ctx context.Context, name string) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByName, name)
	var i Provider
	err := row.Scan(
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProvidersByType = `-- name: ListActiveProvidersByType :many
SELECT name, type, config, priority, is_active, created_at, updated_at
FROM providers
WHERE type = $1
  AND is_active = true
ORDER BY priority ASC, name ASC
`

func (q *Queries) ListActiveProvidersByType(ctx context.Context, type_ string) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listActiveProvidersByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.Name,
			&i.Type,
			&i.Config,
			&i.Priority,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
