// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClaimDelivery(ctx context.Context, arg ClaimDeliveryParams) (NotificationDelivery, error)
	ClaimPendingOutboxEvents(ctx context.Context, arg ClaimPendingOutboxEventsParams) ([]OutboxEvent, error)
	CreateDeliveryAttempt(ctx context.Context, arg CreateDeliveryAttemptParams) (NotificationDeliveryAttempt, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateNotificationDelivery(ctx context.Context, arg CreateNotificationDeliveryParams) (NotificationDelivery, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error)
	DeletePublishedOutboxEvents(ctx context.Context) (int64, error)
	GetDeliveryAttempts(ctx context.Context, deliveryID uuid.UUID) ([]NotificationDeliveryAttempt, error)
	GetDeliveryByID(ctx context.Context, id uuid.UUID) (NotificationDelivery, error)
	GetDeliveryWithNotification(ctx context.Context, id uuid.UUID) (GetDeliveryWithNotificationRow, error)
	GetLatestDeliveryAttempt(ctx context.Context, deliveryID uuid.UUID) (NotificationDeliveryAttempt, error)
	GetNotificationByID(ctx context.Context, id uuid.UUID) (GetNotificationByIDRow, error)
	GetOldestPendingOutboxAgeSeconds(ctx context.Context) (int64, error)
	GetProviderByName(ctx context.Context, name string) (Provider, error)
	ListActiveProvidersByType(ctx context.Context, type_ string) ([]Provider, error)
	ListReadyRetryDeliveries(ctx context.Context, arg ListReadyRetryDeliveriesParams) ([]uuid.UUID, error)
	MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) (int64, error)
	MarkDeliveryRetry(ctx context.Context, arg MarkDeliveryRetryParams) (int64, error)
	MarkDeliverySent(ctx context.Context, arg MarkDeliverySentParams) (int64, error)
	MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error
	MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error
	NotificationExistsByEventID(ctx context.Context, eventID string) (bool, error)
	ReclaimAbandonedDeliveries(ctx context.Context, lockedAt pgtype.Timestamptz) ([]NotificationDelivery, error)
	ReleaseOutboxEventLock(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
