// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelDelivery(ctx context.Context, id uuid.UUID) (NotificationDelivery, error)
	ClaimDeliveries(ctx context.Context, arg ClaimDeliveriesParams) ([]NotificationDelivery, error)
	ClaimNextDelivery(ctx context.Context, workerID pgtype.Text) (NotificationDelivery, error)
	CreateDeliveryAttempt(ctx context.Context, arg CreateDeliveryAttemptParams) (NotificationDeliveryAttempt, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateNotificationDelivery(ctx context.Context, arg CreateNotificationDeliveryParams) (NotificationDelivery, error)
	DeactivateProvider(ctx context.Context, name string) (Provider, error)
	GetDeliveryAttempt(ctx context.Context, arg GetDeliveryAttemptParams) (NotificationDeliveryAttempt, error)
	GetDeliveryByID(ctx context.Context, id uuid.UUID) (NotificationDelivery, error)
	GetDeliveryByNotificationAndChannel(ctx context.Context, arg GetDeliveryByNotificationAndChannelParams) (NotificationDelivery, error)
	GetNotificationByEventID(ctx context.Context, eventID string) (Notification, error)
	GetProviderByName(ctx context.Context, name string) (Provider, error)
	ListActiveProvidersByType(ctx context.Context, type_ string) ([]Provider, error)
	ListDeliveriesByNotificationID(ctx context.Context, notificationID uuid.UUID) ([]NotificationDelivery, error)
	ListDeliveryAttempts(ctx context.Context, deliveryID uuid.UUID) ([]NotificationDeliveryAttempt, error)
	MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) (NotificationDelivery, error)
	MarkDeliverySent(ctx context.Context, arg MarkDeliverySentParams) (NotificationDelivery, error)
	ReclaimStaleDeliveries(ctx context.Context, leaseTimeout pgtype.Interval) ([]NotificationDelivery, error)
	ScheduleDeliveryRetry(ctx context.Context, arg ScheduleDeliveryRetryParams) (NotificationDelivery, error)
	UpsertProvider(ctx context.Context, arg UpsertProviderParams) (Provider, error)
}

var _ Querier = (*Queries)(nil)
